### ISSUE TITLE
Backup fails: pipelined request failed: stream error received

### ISSUE THREAD

**Issue by abbbi** [tizbac/pmoxs3backuproxy#25] opened 2024-08-13 14:00 UTC
hi,

playing around with removing and re-executing backups due to latest PR. Sometimes i noticed backups to fail, it seems easier to reproduce if an backup is started and *all* chunks are already in S3.  Ive seen it with older builds too, but though maybe its an hiccup in my VPN. But this time it appeared locally, too.

Creating a new backup fails via:

```
INFO: scsi1: dirty-bitmap status: existing bitmap was invalid and has been cleared
INFO:  25% (528.0 MiB of 2.0 GiB) in 2s, read: 264.0 MiB/s, write: 164.0 MiB/s
ERROR: backup write data failed: command error: write_data upload error: pipelined request failed: stream error received: not a result of an error
```
debug shows that all chunks are logged via:

```
2024/08/13 15:58:10 [DEBUG] Request:/fixed_chunk?digest=413af336e19d2abc7261349d220c9415393a6fb1cbdc4589e4f456fdccacefe8&encoded-size=1121670&size=4194304&wid=1 Method: POST
2024/08/13 15:58:10 [DEBUG] 413af336e19d2abc7261349d220c9415393a6fb1cbdc4589e4f456fdccacefe8 already in S3
```

so it doesnt have to write any chunk.

`2024/08/13 15:59:43 [WARNING] Removing incomplete backup backups/110|1723557582|vm`

**Comment by abbbi** [comment] 2024-08-13 14:05
There might aswell be another reason for this, maybe the stream processing is wrong. If this happens you can note that the PVE never calls the /finish endpoint:

```
2024/08/13 16:04:08 [DEBUG] 39a1502be2f5121aa19075ce2aecbbe1e12921f9448067dbe772288b97c552e3 already in S3
2024/08/13 16:04:08 [WARNING] Removed incomplete backup backups/110|1723557846|vm
2024/08/13 16:04:09 [DEBUG] Request:/api2/json/access/ticket Method: POST
2024/08/13 16:04:09 [DEBUG] Connection=Keep-Alive, TE
2024/08/13 16:04:09 [DEBUG] Accept-Encoding=gzip
2024/08/13 16:04:09 [DEBUG] User-Agent=libwww-perl/6.68
2024/08/13 16:04:09 [DEBUG] Content-Length=85
2024/08/13 16:04:09 [DEBUG] Content-Type=application/x-www-form-urlencoded
2024/08/13 16:04:09 [DEBUG] Te=deflate,gzip;q=0.3
```

**Comment by tizbac** [comment] 2024-08-13 14:48
It is meant to happen when TCP connection / HTTP2 is broken before finish, if it is marked as incomplete means that HTTP2 is dead, also on regular pbs that is not recoverable afaik
You will anyway have leftover chunks, so if you do backup again before GC it will be much faster

**Comment by abbbi** [comment] 2024-08-13 14:58
> It is meant to happen when TCP connection / HTTP2 is broken before finish, if it is marked as incomplete means that HTTP2 is dead, also on regular pbs that is not recoverable afaik You will anyway have leftover chunks, so if you do backup again before GC it will be much faster

yea, its not due to the fact that there are all chunks there, it seems just to be an hiccup if vzdump is going on.
I can reproduce it with bigger backups (~2GB) but never get this error on small incremental backups.

**Comment by abbbi** [comment] 2024-08-13 16:34
i wonder if that might be some async foo? 

https://git.proxmox.com/?p=pve-qemu.git;a=blob;f=debian/patches/pve/0030-PVE-Backup-Proxmox-backup-patches-for-QEMU.patch;h=fee57fa9902a2075ababc6e909416f2b9f2b0a62;hb=582fd47901356342b8e0bef19d7d8fdc324d2d96#l512

**Comment by abbbi** [comment] 2024-08-13 18:08
It definitely happens if there is no snapshot in the target backup storage.
It drops at random situations, sometimes with:

```
INFO: scsi1: dirty-bitmap status: created new
INFO:   5% (120.0 MiB of 2.0 GiB) in 1s, read: 120.0 MiB/s, write: 120.0 MiB/s
ERROR: backup write data failed: command error: protocol canceled
INFO: aborting backup job
INFO: stopping kvm after backup task
ERROR: Backup of VM 110 failed - backup write data failed: command error: protocol canceled
```
sometimes with:

```
INFO: scsi1: dirty-bitmap status: created new
INFO:  25% (516.0 MiB of 2.0 GiB) in 2s, read: 258.0 MiB/s, write: 258.0 MiB/s
ERROR: backup write data failed: command error: write_data upload error: pipelined request failed: stream error received: not a result of an error
INFO: aborting backup job
INFO: stopping kvm after backup task
```

once there is an existing snapshot in the target storage i cant reproduce the problem anymore no matter how many new chunks are uploaded.

**Comment by abbbi** [comment] 2024-08-14 06:53
Ok, so here is defintely a way to reproduce it:

1) Empty a fresh bucket
2) create an full backup of reasonable size (2 GB)
2) Remove the Snapshot folder in backups/ for the backup you have just created via minio frontend

From this point on any subsequent backup will fail.

**Comment by tizbac** [comment] 2024-08-14 10:57
Can you check if proxmox is passing reuse-csum ? because you would have to remove the FIDX also from "indexed" folder

**Comment by abbbi** [comment] 2024-08-14 11:04
ive tried several things.
Proxmox backup server with an existing backup looks like this:

```
root@pxmx8:/var/log/proxmox-backup/api# find /backup/ | grep -v chunk
/backup/
/backup/vm
/backup/vm/110
/backup/vm/110/2024-08-14T10:59:16Z
/backup/vm/110/2024-08-14T10:59:16Z/client.log.blob
/backup/vm/110/2024-08-14T10:59:16Z/drive-scsi0.img.fidx
/backup/vm/110/2024-08-14T10:59:16Z/index.json.blob
/backup/vm/110/2024-08-14T10:59:16Z/qemu-server.conf.blob
/backup/vm/110/owner
/backup/.lock
```
hitting the remove button removes basically this folder. W/O running GC i can backup the same VM to PBS w/o any issues.
I also tried re-setting the indexed folder, without success.

**Comment by tizbac** [comment] 2024-08-14 13:36
Reproduced it here too

**Comment by abbbi** [comment] 2024-08-14 15:01
reading the proxmox backup client library that is integrated into qemu via C bindings give me the impression that fixed_chunk does return an http response here:

```
                // Phase 1: send data
                let response_future = client
                    .send_upload_request(
                        "POST",
                        "fixed_chunk",
                        Some(param),
                        "application/octet-stream",                                                                                     
                        chunk_data,
                    )
                    .await?;

                // create response future (run that in other task)
                let upload_future = response_future
                    .map_err(Error::from)
                    .and_then(H2Client::h2api_response)
                    .map_ok(move |_| ChunkUploadInfo {
                        digest,
                        offset,
                        size,
                        chunk_is_known: false,
                    })
                    .map_err(|err| format_err!("pipelined request failed: {}", err));
```

thats currently not the case in this implementation.
Maybe the client requires this response to keep going correctly. Note there is an "chunk_is_known" value here, that may be relevant in this situation.

**Comment by tizbac** [comment] 2024-08-14 15:03
I tried and it failed anyway, then it stopped happening :/
Returning { "data" : null }

**Comment by abbbi** [comment] 2024-08-14 15:17
i tried with returning the right array but it doesnt make any difference. the offset is just set manually  not sure if its relevant.

```
2024/08/14 17:14:05 [DEBUG] chunks/6c/e2/a255212fe8821504425807a53bdcf1af07ef145055396f9a79f4b9974536 already in S3
 {"data":{"digest":"6ce2a255212fe8821504425807a53bdcf1af07ef145055396f9a79f4b9974536","offset":2000,"size":4194304,"chunk_is_known":true}}
```

i wonder if it might be an issue with s.Writers beeng accessed concurently in fixed_index and fixed_chunk?

**Comment by tizbac** [comment] 2024-08-14 15:44
More than that judging by the logs, it is uploading multiple chunks at same
time

Il mer 14 ago 2024, 17:18 Michael Ablassmeier ***@***.***> ha
scritto:

**Comment by tizbac** [comment] 2024-08-14 15:45
Actually could be that the body of the post is not read when it is already in S3

**Comment by tizbac** [comment] 2024-08-14 15:49
s3backuplog.DebugPrint("%s already in S3", objectStat.Key)
io.ReadAll(r.Body)

Try adding that io.ReadAll for me now does not happen

**Comment by abbbi** [comment] 2024-08-14 16:17
Im Afk But that would make sense… 👍👍

**Comment by abbbi** [comment] 2024-08-14 22:00
i can confirm this fixes the problem!
PR with slight modifications:

 https://github.com/tizbac/pmoxs3backuproxy/pull/28

**Comment by tizbac** [comment] 2024-08-14 22:13
Merged , i also have been unable to reproduce after adding io.readall

**Closed by tizbac** 2024-08-14 22:13 UTC
